name: Generate Document Insights

on:
  schedule:
    # Run every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-insights:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd 6_Agent_Deployment/backend_rag_pipeline
        pip install -r requirements.txt

    - name: Generate Insights
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      run: |
        cd 6_Agent_Deployment/backend_rag_pipeline/scripts
        python auto_generate_insights.py

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: insights-logs
        path: 6_Agent_Deployment/backend_rag_pipeline/scripts/insights_generation.log
